--joins 

use AdventureWorks2012

create table MYEMPLOYEE(EMPLOYEEID INT,FIRSTNAME VARCHAR(20),LASTNAME VARCHAR(20))


GO

INSERT INTO MYEMPLOYEE VALUES (1,'BOB','ROB')
INSERT INTO MYEMPLOYEE VALUES (2,'MARRY','JEAN')
INSERT INTO MYEMPLOYEE VALUES (4,'HO LEE','FUQ')


update MYEMPLOYEE set EMPLOYEEID=3,firstname='holee' where FIRSTNAME='HO LEE'



create table mysalary (employeeid int, salary float)


insert into mysalary values(1,1000)
insert into mysalary values(2,1500)
insert into mysalary values(3,2000)

select * from MYEMPLOYEE
select * from mysalary

--inner join. With alias 'a' and 'b' along with which column is common among the both tables
select a.EMPLOYEEID,a.FIRSTNAME,a.LASTNAME,b.salary
from myemployee a inner join mysalary b on a.EMPLOYEEID=b.employeeid


create TABLE MYPHONE(EMPLOYEEID INT,PHONENUMBER INT)
INSERT INTO MYPHONE VALUES(1,124123123)
INSERT INTO MYPHONE VALUES(2,666564223)

SELECT * FROM MYPHONE

--OUTER JOIN.

--left join
select * from myemployee a left join MYPHONE b on a.EMPLOYEEID=b.EMPLOYEEID

select a.employeeid,a.firstname,a.lastname,b.phonenumber 
from myemployee a left join MYPHONE b on a.EMPLOYEEID=b.EMPLOYEEID

select * from MYEMPLOYEE
select * from MYPHONE

--right join
 
CREATE TABLE MYPARKING(EMPLOYEEID INT,PARKINGSPOT VARCHAR(20))
INSERT INTO MYPARKING VALUES (1,'A1')
INSERT INTO MYPARKING VALUES (2,'A2')


SELECT * FROM MYEMPLOYEE A RIGHT JOIN MYPARKING B ON A.EMPLOYEEID=B.EMPLOYEEID

SELECT * FROM MYPARKING
SELECT * FROM MYEMPLOYEE


SELECT b.FIRSTNAME,b.LASTNAME,a.PARKINGSPOT FROM MYPARKING A RIGHT JOIN MYEMPLOYEE B ON A.EMPLOYEEID=B.EMPLOYEEID

--full outer join

CREATE TABLE MYCUSTOMER (CUSTOMERID INT, CUSTOMERNAME VARCHAR(20))


INSERT INTO MYCUSTOMER VALUES (1,'MANDY')
INSERT INTO MYCUSTOMER VALUES (2,'BOB')

UPDATE MYCUSTOMER SET CUSTOMERID=3 WHERE CUSTOMERID=2 

CREATE TABLE MYORDER(ORDERID INT,ORDERNAME VARCHAR(20),CUSTOMERID INT)

INSERT INTO MYORDER VALUES(1,'samosa',1)
INSERT INTO MYORDER VALUES(2,'samosa',2)
INSERT INTO MYORDER VALUES(3,'samosa',7)
INSERT INTO MYORDER VALUES(4,'samosa',8)

select * from MYCUSTOMER
select * from MYORDER

select a.CUSTOMERID,a.CUSTOMERNAME,b.ORDERID,b.ORDERNAME from MYCUSTOMER a full outer join MYORDER b on a.CUSTOMERID=b.CUSTOMERID


--CROSS JOINS	


SELECT * FROM MYCUSTOMER
SELECT * FROM MYEMPLOYEE
SELECT * FROM MYCUSTOMER,MYEMPLOYEE
--OR SELECT * FROM MYCUSTOMER OUTER JOIN MYEMPLOYEE


